# Generated by Django 5.2.13 on 2026-04-29 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Canción')),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Género Musical')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM (Pulsos por minuto)')),
                ('tonalidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tonalidad (Ej: Do Mayor, Am)')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instrumento', models.CharField(max_length=50, verbose_name='Instrumento / Voz')),
                ('notas_o_tablatura', models.TextField(blank=True, null=True, verbose_name='Notas, acordes o indicaciones')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='catalogo.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_audio', models.FileField(upload_to='grabaciones/%Y/%m/', verbose_name='Archivo de Audio')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='catalogo.seccionpista')),
            ],
        ),
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('APRENDIENDO', 'Aprendiendo'), ('DOMINADA', 'Dominada'), ('DESCARTADA', 'Descartada')], default='APRENDIENDO', max_length=20)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertorio', to='bandas.banda')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.cancion')),
            ],
            options={
                'unique_together': {('banda', 'cancion')},
            },
        ),
    ]
