# Generated by Django 5.2.13 on 2026-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='repertorio',
            name='ultima_vez_tocada',
            field=models.DateField(blank=True, null=True, verbose_name='Última vez tocada en ensayo/en vivo'),
        ),
        migrations.AlterField(
            model_name='repertorio',
            name='estado',
            field=models.CharField(choices=[('POR_TOCAR', 'Nuevas / Por Tocar'), ('APRENDIENDO', 'En Aprendizaje'), ('ACTIVA', 'Repertorio Activo')], default='POR_TOCAR', max_length=20),
        ),
    ]
