# Generated by Django 5.2.13 on 2026-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_cancion_options_repertorio_ultima_vez_tocada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='partituras/%Y/%m/', verbose_name='Partitura o Letra (PDF)'),
        ),
        migrations.AlterField(
            model_name='repertorio',
            name='estado',
            field=models.CharField(choices=[('SUGERIDA', 'Sugerida (Pendiente de Aprobación)'), ('POR_TOCAR', 'Nuevas / Por Tocar'), ('APRENDIENDO', 'En Aprendizaje'), ('ACTIVA', 'Repertorio Activo')], default='POR_TOCAR', max_length=20),
        ),
    ]
