# Generated by Django 5.2.13 on 2026-05-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, help_text='Breve descripción del músico, influencias o experiencia.', null=True, verbose_name='Biografía / Descripción'),
        ),
    ]
