# Generated by Django 5.2.13 on 2026-05-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instrumento_principal',
            field=models.CharField(blank=True, choices=[('VOZ', 'Voz'), ('GUITARRA', 'Guitarra'), ('BAJO', 'Bajo'), ('BATERIA', 'Batería'), ('PIANO', 'Piano / Teclado'), ('GUITARRA_VOZ', 'Guitarra & Voz'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Instrumento Principal'),
        ),
    ]
