# Generated by Django 5.2.13 on 2026-08-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0014_instrumento'),
        ('usuarios', '0003_alter_usuario_instrumento_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bandas.instrumento',),
        ),
    ]
