# Generated by Django 5.2.13 on 2026-09-28 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_preapproval_id', models.CharField(blank=True, help_text='ID de la suscripción (preapproval) en MercadoPago', max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente de autorización'), ('authorized', 'Autorizada (Pro activo)'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('payload_bruto', models.JSONField(blank=True, help_text='Copia cruda de la notificación recibida, para depurar.', null=True)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.suscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_recibido'],
            },
        ),
    ]
