"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import mimetypes
import dj_database_url  # type: ignore
from dotenv import load_dotenv  # type: ignore

# Le enseñamos a Django a transmitir formatos de audio modernos correctamente
mimetypes.add_type("audio/webm", ".webm", True)
mimetypes.add_type("audio/ogg", ".ogg", True)
mimetypes.add_type("audio/mp4", ".m4a", True)
mimetypes.add_type("audio/mpeg", ".mp3", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6e-mqj24!tc%4#g4jk3%zu2#b&$$jzzrsc7f6_t(0dcsr9v5x('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    # --- Librerías de terceros ---
    'rest_framework',
    'rest_framework_simplejwt',

    # --- Aplicaciones de tu proyecto ---
    'usuarios',
    'bandas',
    'catalogo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL_LOCAL = "postgres://sebastian:bandadmin2030@127.0.0.1:5432/bandadmin_db"
env_url = os.environ.get('DATABASE_URL', DATABASE_URL_LOCAL)

DATABASES = {
    'default': dj_database_url.parse(
        env_url,
        conn_max_age=600
    )
}

# Desactivar SSL estrictamente si estamos en modo desarrollo local
if os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true':
    DATABASES['default']['OPTIONS'] = {}
else:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Indica que nuestro modelo personalizado manejará la autenticación
AUTH_USER_MODEL = 'usuarios.Usuario'

# --- Configuración de CORS ---
# Permitimos que Next.js (puerto 3000) se comunique con Django sin ser bloqueado
CORS_ALLOW_ALL_ORIGINS = True

# También es buena práctica permitir el envío de credenciales/cookies en el futuro
CORS_ALLOW_CREDENTIALS = True

# --- Configuración de Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Si quieres que toda la API sea privada por defecto, descomenta las siguientes líneas:
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ]
}

# --- Configuración básica de JWT ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # El token dura 1 día
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}
# --- CONFIGURACIÓN DE ARCHIVOS MULTIMEDIA EN PRODUCCIÓN ---

if not DEBUG:
    # Si estamos en producción, usamos Cloudinary como almacenamiento remoto
    INSTALLED_APPS += [
        'cloudinary_storage',
        'cloudinary',
    ]

    # Credenciales que obtienes al crearte una cuenta gratuita en Cloudinary
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
        'RESOURCE_TYPE': 'auto'  # Crucial para que reconozca tanto PDFs como audios .webm
    }

    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    # Si estamos en local (DEBUG = True), seguimos guardando en la carpeta media de tu PC
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
# La URL que aparecerá en el navegador (ej: http://127.0.0.1:8000/media/...)
MEDIA_URL = '/media/'

# La carpeta física en tu computador donde se guardarán los PDFs y audios
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CONFIGURACIÓN DE CORREOS SEGURA ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# CAMBIO CRÍTICO: Ahora leemos las credenciales desde el entorno
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
