# Generated by Django 5.2.13 on 2026-04-28 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Banda')),
                ('genero_musical', models.CharField(blank=True, max_length=50, null=True, verbose_name='Género Musical')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Inicio del Ensayo')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fin del Ensayo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación/Link')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='bandas.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol en la banda (Ej: Voz 1, Batería)')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandas.banda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'banda', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='banda',
            name='integrantes',
            field=models.ManyToManyField(related_name='bandas', through='bandas.Membresia', to=settings.AUTH_USER_MODEL),
        ),
    ]
