# Generated by Django 5.2.13 on 2026-05-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='es_administrador',
            field=models.BooleanField(default=False, verbose_name='¿Es administrador/líder de la banda?'),
        ),
    ]
