# Generated by Django 5.2.13 on 2026-05-12 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_membresia_es_administrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensayo',
            options={'ordering': ['fecha_hora_inicio'], 'verbose_name': 'Ensayo', 'verbose_name_plural': 'Ensayos'},
        ),
        migrations.AddField(
            model_name='ensayo',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='ensayos_asistidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Ej: Revisar el setlist para el viernes', null=True, verbose_name='Objetivo del ensayo'),
        ),
    ]
