# Generated by Django 5.2.13 on 2026-05-12 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_ensayo_options_ensayo_asistentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='bandas.banda'),
        ),
    ]
