# Generated by Django 5.2.13 on 2026-05-14 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_invitacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Sala de ensayo, Cuerdas, Grabación', max_length=255)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_gasto', models.DateField(auto_now_add=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='bandas.banda')),
                ('pagado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
