# Generated by Django 5.2.13 on 2026-05-18 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membresia',
            unique_together={('usuario', 'banda')},
        ),
        migrations.AlterField(
            model_name='membresia',
            name='rol',
            field=models.CharField(choices=[('Líder', 'Líder'), ('Músico', 'Músico')], default='Músico', max_length=50, verbose_name='Rol en la banda'),
        ),
    ]
