# Generated by Django 5.2.13 on 2026-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_alter_membresia_unique_together_alter_membresia_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='comprobante_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link del comprobante (Boleta, Drive, etc.)'),
        ),
    ]
