# Generated by Django 5.2.13 on 2026-05-18 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_gasto_comprobante_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Por tocar', 'Por tocar'), ('En Aprendizaje', 'En Aprendizaje'), ('Repertorio Activo', 'Repertorio Activo')], default='Por tocar', max_length=50)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='bandas.banda')),
            ],
        ),
    ]
