# Generated by Django 5.2.13 on 2026-05-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_cancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='partitura',
            field=models.FileField(blank=True, null=True, upload_to='partituras/', verbose_name='Partitura o Archivo adjunto (PDF)'),
        ),
    ]
