# Generated by Django 5.2.13 on 2026-05-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0010_cancion_partitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='en_setlist',
            field=models.BooleanField(default=False, verbose_name='¿Está en el Setlist de esta semana?'),
        ),
    ]
