# Generated by Django 5.2.13 on 2026-05-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0011_cancion_en_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo_audio',
            field=models.FileField(blank=True, null=True, upload_to='canciones/', verbose_name='Archivo de Audio (Maqueta/Grabación)'),
        ),
    ]
