# Generated by Django 5.2.13 on 2026-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0012_cancion_archivo_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='es_maqueta',
            field=models.BooleanField(default=False, verbose_name='¿Es una maqueta/grabación de referencia?'),
        ),
    ]
