# Generated by Django 5.2.13 on 2026-08-29 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0013_cancion_es_maqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('familia', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
