# Generated by Django 5.2.13 on 2026-09-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0014_instrumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Gibson Gold Top Les Paul P90, Monitor Activo Wharfedale...', max_length=150)),
                ('tipo', models.CharField(choices=[('INSTRUMENTO', 'Instrumento (Guitarras, Bajos, Teclados)'), ('MICROFONIA', 'Microfonía (Dinámicos, Condensador, Inalámbricos)'), ('MONITOREO', 'Monitoreo (In-Ears, Monitores Activos)'), ('BACKLINE', 'Backline (Amplificadores, Baterías)'), ('ACCESORIOS', 'Accesorios (Cables XLR, Cajas Directas, Pedales)')], default='INSTRUMENTO', max_length=20)),
                ('marca_modelo', models.CharField(blank=True, help_text='Ej: Shure SM58, Behringer DI20, Klotz XLR', max_length=150, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('propio', models.BooleanField(default=True, help_text='¿La banda lleva este equipo o lo debe proveer el local?')),
                ('requiere_corriente', models.BooleanField(default=False, help_text='¿Necesita enchufe 220v en el escenario?')),
                ('requiere_phantom_power', models.BooleanField(default=False, help_text='¿Necesita +48v desde la consola?')),
                ('notas_tecnicas', models.TextField(blank=True, help_text="Instrucciones para el sonidista. Ej: 'Se usa con caja directa', 'Microfonear al centro del cono'.", null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='bandas.banda')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
