# Generated by Django 5.2.13 on 2026-09-28 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0015_equipamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Voz principal, Línea de bajo, Batería, Guitarra base', max_length=100, verbose_name='Nombre del stem')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='bandas.cancion')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pistas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pista (Stem)',
                'verbose_name_plural': 'Pistas (Stems)',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_audio', models.FileField(upload_to='multitrack/tomas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='bandas.pista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas_grabadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toma',
                'verbose_name_plural': 'Tomas',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('momento_segundos', models.FloatField(help_text='Posición en segundos dentro de la forma de onda', verbose_name='Segundo exacto del comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_audio', to=settings.AUTH_USER_MODEL)),
                ('toma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='bandas.toma')),
            ],
            options={
                'verbose_name': 'Comentario de audio',
                'verbose_name_plural': 'Comentarios de audio',
                'ordering': ['momento_segundos'],
            },
        ),
    ]
