# Generated by Django 5.2.13 on 2026-09-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0016_pista_toma_comentarioaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='tech_riders_exportados',
            field=models.PositiveIntegerField(default=0, help_text='Cuántas veces se descargó el PDF del Tech Rider (limitado en el plan Free).', verbose_name='Tech Riders exportados'),
        ),
    ]
